import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Static Hosting","description":"","frontmatter":{},"headers":[],"relativePath":"guide/static-hosting.md","filePath":"guide/static-hosting.md"}');
const _sfc_main = { name: "guide/static-hosting.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="static-hosting" tabindex="-1">Static Hosting <a class="header-anchor" href="#static-hosting" aria-label="Permalink to &quot;Static Hosting&quot;">​</a></h1><p>AYB&#39;s hosting support is a Phase 1 feature for serving prebuilt static sites. It is intentionally narrow: build your frontend locally, then deploy the output directory with the CLI.</p><h2 id="what-phase-1-includes" tabindex="-1">What Phase 1 includes <a class="header-anchor" href="#what-phase-1-includes" aria-label="Permalink to &quot;What Phase 1 includes&quot;">​</a></h2><ul><li>CLI-first deploys with <code>ayb sites deploy &lt;site-id-or-slug&gt; --dir &lt;build-dir&gt;</code></li><li>Admin dashboard site CRUD and deploy history actions</li><li>Host-based serving for derived domains and verified custom domains</li><li>SPA fallback via per-site <code>spa_mode</code></li><li>Deploy lifecycle management: uploading, live, superseded, failed</li></ul><h2 id="deploy-flow" tabindex="-1">Deploy flow <a class="header-anchor" href="#deploy-flow" aria-label="Permalink to &quot;Deploy flow&quot;">​</a></h2><p>Build your frontend locally first, then upload the generated directory:</p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> run</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> build</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">ayb</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> sites</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> deploy</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> marketing</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --dir</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> ./dist</span></span></code></pre></div><p>The deploy directory must include <code>index.html</code>. AYB uploads files in deterministic order and promotes the resulting deploy separately from the upload step.</p><h2 id="runtime-behavior" tabindex="-1">Runtime behavior <a class="header-anchor" href="#runtime-behavior" aria-label="Permalink to &quot;Runtime behavior&quot;">​</a></h2><p>Static hosting only handles normal site traffic. AYB bypasses site-runtime serving for:</p><ul><li><code>/api</code></li><li>the configured admin path</li><li><code>/health</code></li><li><code>/favicon.ico</code></li></ul><p>Only <code>GET</code> and <code>HEAD</code> requests are served by the site runtime. Other methods bypass site hosting and continue to the normal server handlers.</p><p>When <code>spa_mode</code> is enabled, AYB serves <code>index.html</code> for missing application routes. When <code>spa_mode</code> is disabled, missing paths return a normal 404.</p><h2 id="what-phase-1-does-not-include" tabindex="-1">What Phase 1 does not include <a class="header-anchor" href="#what-phase-1-does-not-include" aria-label="Permalink to &quot;What Phase 1 does not include&quot;">​</a></h2><p>These are intentional Phase 2+ deferrals, not broken features:</p><ul><li>Git-triggered deploys</li><li>Server-side build execution</li><li>Dashboard file uploads for deploy artifacts</li><li>Preview or staging deploy URLs</li><li>Per-site TLS management</li><li>Build logs</li><li>Deploy diffing</li></ul><h2 id="related-guides" tabindex="-1">Related guides <a class="header-anchor" href="#related-guides" aria-label="Permalink to &quot;Related guides&quot;">​</a></h2><ul><li><a href="/guide/cli.html">CLI Reference</a></li><li><a href="/guide/custom-domains.html">Custom Domains</a></li><li><a href="/guide/configuration.html">Configuration</a></li><li><a href="/guide/deployment.html">Deployment</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("guide/static-hosting.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const staticHosting = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  staticHosting as default
};
